coverage:
  status:
    project:
      default:
        threshold: 1%
codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project: 
        default:
            enabled: yes
            target: 90%
            threshold: 1%
    patch: 
        default:
            enabled: yes
            target: 95%
            threshold: 1%
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
